version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # default location of `.github/workflows`
    ignore:
      - dependency-name: "home-assistant/builder" # Newer versions will not support armv7 anymore! https://github.com/home-assistant/builder/releases/tag/2025.11.0
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Berlin"
  
  - package-ecosystem: "nuget"
    directory: "/portainer-monitor-addon/source"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Berlin"
